api_login_check:
    path: /api/login_check
homepage:
    path:     /
    defaults: { _controller: docsman.home_controller:indexAction }

project:
    resource: '@AppBundle/Resources/config/routing.project.yml'

document:
    resource: '@AppBundle/Resources/config/routing.document.yml'
