Docsman\Model\Document:
    type: entity
    table: document
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name: ~
        content: ~
        isTrash:
            type: boolean
        creationDate:
            type: datetime
    manyToOne:
        project:
            targetEntity: Docsman\Model\Project
            inversedBy: documents
            joinColumn:
                name: project_id
                referencedColumnName: id
